<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-26T13:01:01 IST" name="Suite" finished-at="2022-12-26T13:01:35 IST" duration-ms="34322">
    <groups>
    </groups>
    <test started-at="2022-12-26T13:01:01 IST" name="Test" finished-at="2022-12-26T13:01:35 IST" duration-ms="34322">
      <class name="com.TestLayer.LogginTest">
        <test-method is-config="true" signature="start()[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:01 IST" name="start" finished-at="2022-12-26T13:01:02 IST" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method is-config="true" signature="browserLaunch(java.lang.String)[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:02 IST" name="browserLaunch" finished-at="2022-12-26T13:01:19 IST" duration-ms="16947" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:19 IST" name="login" finished-at="2022-12-26T13:01:34 IST" duration-ms="15314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="verifyLoginTest()[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:34 IST" name="verifyLoginTest" finished-at="2022-12-26T13:01:34 IST" duration-ms="47" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://suite8demo.suiteondemand.com/#/home] but found [https://suite8demo.suiteondemand.com/#/Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://suite8demo.suiteondemand.com/#/home] but found [https://suite8demo.suiteondemand.com/#/Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.TestLayer.LogginTest.verifyLoginTest(LogginTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginTest -->
        <test-method is-config="true" signature="browserClose()[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:34 IST" name="browserClose" finished-at="2022-12-26T13:01:35 IST" duration-ms="772" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserClose -->
        <test-method is-config="true" signature="stop()[pri:0, instance:com.TestLayer.LogginTest@158d2680]" started-at="2022-12-26T13:01:35 IST" name="stop" finished-at="2022-12-26T13:01:35 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop -->
      </class> <!-- com.TestLayer.LogginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
